package com.KursTakip.Dto;
// Generated 02-Apr-2019 16:18:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KullaniciId generated by hbm2java
 */
@Embeddable
public class KullaniciId  implements java.io.Serializable {


     private String kullaniciAdi;
     private String sifre;

    public KullaniciId() {
    }

    public KullaniciId(String kullaniciAdi, String sifre) {
       this.kullaniciAdi = kullaniciAdi;
       this.sifre = sifre;
    }
   


    @Column(name="KullaniciAdi", nullable=false, length=15)
    public String getKullaniciAdi() {
        return this.kullaniciAdi;
    }
    
    public void setKullaniciAdi(String kullaniciAdi) {
        this.kullaniciAdi = kullaniciAdi;
    }


    @Column(name="Sifre", nullable=false, length=10)
    public String getSifre() {
        return this.sifre;
    }
    
    public void setSifre(String sifre) {
        this.sifre = sifre;
    }




}


