package com.KursTakip.Dto;
// Generated 02-Apr-2019 16:18:32 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Kullanici generated by hbm2java
 */
@Entity
@Table(name="kullanici"
    ,catalog="dershane"
)
public class Kullanici  implements java.io.Serializable {


     private KullaniciId id;

    public Kullanici() {
    }

    public Kullanici(KullaniciId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="kullaniciAdi", column=@Column(name="KullaniciAdi", nullable=false, length=15) ), 
        @AttributeOverride(name="sifre", column=@Column(name="Sifre", nullable=false, length=10) ) } )
    public KullaniciId getId() {
        return this.id;
    }
    
    public void setId(KullaniciId id) {
        this.id = id;
    }




}


