package com.KursTakip.Dto;
// Generated 02-Apr-2019 16:18:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ogrenci generated by hbm2java
 */
@Entity
@Table(name="ogrenci"
    ,catalog="dershane"
)
public class Ogrenci  implements java.io.Serializable {


     private Integer ogrId;
     private Integer numara;
     private String ad;
     private String soyad;
     private String tc;
     private Date dgmTarih;
     private Date kayitTarih;
     private String dgmYer;
     private String cinsiyet;
     private String kanGrp;
     private String referans;
     private String resimPath;
     private String notlar;
     private String servisGuzergah;
     private String okul;
     private String sinif;
     private String seriNo;
     private String il;
     private String ilce;
     private String ciltNo;
     private String aileSiraNo;
     private String anneAdSoyad;
     private String anneTc;
     private Date anneDgmTarih;
     private String anneMeslek;
     private String anneEgitim;
     private String annTelefon;
     private String babaAdSoyad;
     private String babaTc;
     private Date babaDgmTarih;
     private String babaMeslek;
     private String babaEgitim;
     private String babaTelefon;
     private String ogrenimSekli;
     private Set<Sozlesme> sozlesmes = new HashSet(0);

    public Ogrenci() {
    }

	
    public Ogrenci(String tc) {
        this.tc = tc;
    }
    public Ogrenci(Integer numara, String ad, String soyad, String tc, Date dgmTarih, Date kayitTarih, String dgmYer, String cinsiyet, String kanGrp, String referans, String resimPath, String notlar, String servisGuzergah, String okul, String sinif, String seriNo, String il, String ilce, String ciltNo, String aileSiraNo, String anneAdSoyad, String anneTc, Date anneDgmTarih, String anneMeslek, String anneEgitim, String annTelefon, String babaAdSoyad, String babaTc, Date babaDgmTarih, String babaMeslek, String babaEgitim, String babaTelefon, String ogrenimSekli, Set sozlesmes) {
       this.numara = numara;
       this.ad = ad;
       this.soyad = soyad;
       this.tc = tc;
       this.dgmTarih = dgmTarih;
       this.kayitTarih = kayitTarih;
       this.dgmYer = dgmYer;
       this.cinsiyet = cinsiyet;
       this.kanGrp = kanGrp;
       this.referans = referans;
       this.resimPath = resimPath;
       this.notlar = notlar;
       this.servisGuzergah = servisGuzergah;
       this.okul = okul;
       this.sinif = sinif;
       this.seriNo = seriNo;
       this.il = il;
       this.ilce = ilce;
       this.ciltNo = ciltNo;
       this.aileSiraNo = aileSiraNo;
       this.anneAdSoyad = anneAdSoyad;
       this.anneTc = anneTc;
       this.anneDgmTarih = anneDgmTarih;
       this.anneMeslek = anneMeslek;
       this.anneEgitim = anneEgitim;
       this.annTelefon = annTelefon;
       this.babaAdSoyad = babaAdSoyad;
       this.babaTc = babaTc;
       this.babaDgmTarih = babaDgmTarih;
       this.babaMeslek = babaMeslek;
       this.babaEgitim = babaEgitim;
       this.babaTelefon = babaTelefon;
       this.ogrenimSekli = ogrenimSekli;
       this.sozlesmes = sozlesmes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ogrId", nullable=false)
    public Integer getOgrId() {
        return this.ogrId;
    }
    
    public void setOgrId(Integer ogrId) {
        this.ogrId = ogrId;
    }

    
    @Column(name="numara", unique=true)
    public Integer getNumara() {
        return this.numara;
    }
    
    public void setNumara(Integer numara) {
        this.numara = numara;
    }

    
    @Column(name="ad", length=15)
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }

    
    @Column(name="soyad", length=15)
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }

    
    @Column(name="tc", nullable=false, length=11)
    public String getTc() {
        return this.tc;
    }
    
    public void setTc(String tc) {
        this.tc = tc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dgmTarih", length=10)
    public Date getDgmTarih() {
        return this.dgmTarih;
    }
    
    public void setDgmTarih(Date dgmTarih) {
        this.dgmTarih = dgmTarih;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="kayitTarih", length=10)
    public Date getKayitTarih() {
        return this.kayitTarih;
    }
    
    public void setKayitTarih(Date kayitTarih) {
        this.kayitTarih = kayitTarih;
    }

    
    @Column(name="dgmYer", length=15)
    public String getDgmYer() {
        return this.dgmYer;
    }
    
    public void setDgmYer(String dgmYer) {
        this.dgmYer = dgmYer;
    }

    
    @Column(name="cinsiyet", length=5)
    public String getCinsiyet() {
        return this.cinsiyet;
    }
    
    public void setCinsiyet(String cinsiyet) {
        this.cinsiyet = cinsiyet;
    }

    
    @Column(name="kanGrp", length=10)
    public String getKanGrp() {
        return this.kanGrp;
    }
    
    public void setKanGrp(String kanGrp) {
        this.kanGrp = kanGrp;
    }

    
    @Column(name="referans", length=15)
    public String getReferans() {
        return this.referans;
    }
    
    public void setReferans(String referans) {
        this.referans = referans;
    }

    
    @Column(name="resimPath", length=65)
    public String getResimPath() {
        return this.resimPath;
    }
    
    public void setResimPath(String resimPath) {
        this.resimPath = resimPath;
    }

    
    @Column(name="notlar", length=150)
    public String getNotlar() {
        return this.notlar;
    }
    
    public void setNotlar(String notlar) {
        this.notlar = notlar;
    }

    
    @Column(name="servisGuzergah", length=100)
    public String getServisGuzergah() {
        return this.servisGuzergah;
    }
    
    public void setServisGuzergah(String servisGuzergah) {
        this.servisGuzergah = servisGuzergah;
    }

    
    @Column(name="okul", length=20)
    public String getOkul() {
        return this.okul;
    }
    
    public void setOkul(String okul) {
        this.okul = okul;
    }

    
    @Column(name="sinif", length=15)
    public String getSinif() {
        return this.sinif;
    }
    
    public void setSinif(String sinif) {
        this.sinif = sinif;
    }

    
    @Column(name="seriNo", length=7)
    public String getSeriNo() {
        return this.seriNo;
    }
    
    public void setSeriNo(String seriNo) {
        this.seriNo = seriNo;
    }

    
    @Column(name="il", length=7)
    public String getIl() {
        return this.il;
    }
    
    public void setIl(String il) {
        this.il = il;
    }

    
    @Column(name="ilce", length=15)
    public String getIlce() {
        return this.ilce;
    }
    
    public void setIlce(String ilce) {
        this.ilce = ilce;
    }

    
    @Column(name="ciltNo", length=7)
    public String getCiltNo() {
        return this.ciltNo;
    }
    
    public void setCiltNo(String ciltNo) {
        this.ciltNo = ciltNo;
    }

    
    @Column(name="aileSiraNo", length=7)
    public String getAileSiraNo() {
        return this.aileSiraNo;
    }
    
    public void setAileSiraNo(String aileSiraNo) {
        this.aileSiraNo = aileSiraNo;
    }

    
    @Column(name="anneAdSoyad", length=15)
    public String getAnneAdSoyad() {
        return this.anneAdSoyad;
    }
    
    public void setAnneAdSoyad(String anneAdSoyad) {
        this.anneAdSoyad = anneAdSoyad;
    }

    
    @Column(name="anneTc", length=11)
    public String getAnneTc() {
        return this.anneTc;
    }
    
    public void setAnneTc(String anneTc) {
        this.anneTc = anneTc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="anneDgmTarih", length=10)
    public Date getAnneDgmTarih() {
        return this.anneDgmTarih;
    }
    
    public void setAnneDgmTarih(Date anneDgmTarih) {
        this.anneDgmTarih = anneDgmTarih;
    }

    
    @Column(name="anneMeslek", length=15)
    public String getAnneMeslek() {
        return this.anneMeslek;
    }
    
    public void setAnneMeslek(String anneMeslek) {
        this.anneMeslek = anneMeslek;
    }

    
    @Column(name="anneEgitim", length=10)
    public String getAnneEgitim() {
        return this.anneEgitim;
    }
    
    public void setAnneEgitim(String anneEgitim) {
        this.anneEgitim = anneEgitim;
    }

    
    @Column(name="annTelefon", length=16)
    public String getAnnTelefon() {
        return this.annTelefon;
    }
    
    public void setAnnTelefon(String annTelefon) {
        this.annTelefon = annTelefon;
    }

    
    @Column(name="babaAdSoyad", length=45)
    public String getBabaAdSoyad() {
        return this.babaAdSoyad;
    }
    
    public void setBabaAdSoyad(String babaAdSoyad) {
        this.babaAdSoyad = babaAdSoyad;
    }

    
    @Column(name="babaTc", length=11)
    public String getBabaTc() {
        return this.babaTc;
    }
    
    public void setBabaTc(String babaTc) {
        this.babaTc = babaTc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="babaDgmTarih", length=10)
    public Date getBabaDgmTarih() {
        return this.babaDgmTarih;
    }
    
    public void setBabaDgmTarih(Date babaDgmTarih) {
        this.babaDgmTarih = babaDgmTarih;
    }

    
    @Column(name="babaMeslek", length=45)
    public String getBabaMeslek() {
        return this.babaMeslek;
    }
    
    public void setBabaMeslek(String babaMeslek) {
        this.babaMeslek = babaMeslek;
    }

    
    @Column(name="babaEgitim", length=45)
    public String getBabaEgitim() {
        return this.babaEgitim;
    }
    
    public void setBabaEgitim(String babaEgitim) {
        this.babaEgitim = babaEgitim;
    }

    
    @Column(name="babaTelefon", length=45)
    public String getBabaTelefon() {
        return this.babaTelefon;
    }
    
    public void setBabaTelefon(String babaTelefon) {
        this.babaTelefon = babaTelefon;
    }

    
    @Column(name="ogrenimSekli", length=15)
    public String getOgrenimSekli() {
        return this.ogrenimSekli;
    }
    
    public void setOgrenimSekli(String ogrenimSekli) {
        this.ogrenimSekli = ogrenimSekli;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ogrenci")
    public Set<Sozlesme> getSozlesmes() {
        return this.sozlesmes;
    }
    
    public void setSozlesmes(Set<Sozlesme> sozlesmes) {
        this.sozlesmes = sozlesmes;
    }




}


