package com.KursTakip.Dto;
// Generated 02-Apr-2019 16:18:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sozlesme generated by hbm2java
 */
@Entity
@Table(name="sozlesme"
    ,catalog="dershane"
)
public class Sozlesme  implements java.io.Serializable {


     private int sozlesmeId;
     private Ogrenci ogrenci;
     private Date tarih;
     private BigDecimal toplamTutar;
     private BigDecimal kalanBorc;
     private BigDecimal pesinat;
     private String borcluAd;
     private String borcluTelefon;
     private String kefilAd;
     private String sozlesmeNot;
     private Date sozlesmeVadeTarih;

    public Sozlesme() {
    }

	
    public Sozlesme(int sozlesmeId) {
        this.sozlesmeId = sozlesmeId;
    }
    public Sozlesme(int sozlesmeId, Ogrenci ogrenci, Date tarih, BigDecimal toplamTutar, BigDecimal kalanBorc, BigDecimal pesinat, String borcluAd, String borcluTelefon, String kefilAd, String sozlesmeNot, Date sozlesmeVadeTarih) {
       this.sozlesmeId = sozlesmeId;
       this.ogrenci = ogrenci;
       this.tarih = tarih;
       this.toplamTutar = toplamTutar;
       this.kalanBorc = kalanBorc;
       this.pesinat = pesinat;
       this.borcluAd = borcluAd;
       this.borcluTelefon = borcluTelefon;
       this.kefilAd = kefilAd;
       this.sozlesmeNot = sozlesmeNot;
       this.sozlesmeVadeTarih = sozlesmeVadeTarih;
    }
   
     @Id 

    
    @Column(name="sozlesmeId", nullable=false)
    public int getSozlesmeId() {
        return this.sozlesmeId;
    }
    
    public void setSozlesmeId(int sozlesmeId) {
        this.sozlesmeId = sozlesmeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ogrId")
    public Ogrenci getOgrenci() {
        return this.ogrenci;
    }
    
    public void setOgrenci(Ogrenci ogrenci) {
        this.ogrenci = ogrenci;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tarih", length=10)
    public Date getTarih() {
        return this.tarih;
    }
    
    public void setTarih(Date tarih) {
        this.tarih = tarih;
    }

    
    @Column(name="toplamTutar", precision=14)
    public BigDecimal getToplamTutar() {
        return this.toplamTutar;
    }
    
    public void setToplamTutar(BigDecimal toplamTutar) {
        this.toplamTutar = toplamTutar;
    }

    
    @Column(name="kalanBorc")
    public BigDecimal getKalanBorc() {
        return this.kalanBorc;
    }
    
    public void setKalanBorc(BigDecimal kalanBorc) {
        this.kalanBorc = kalanBorc;
    }

    
    @Column(name="pesinat", precision=14)
    public BigDecimal getPesinat() {
        return this.pesinat;
    }
    
    public void setPesinat(BigDecimal pesinat) {
        this.pesinat = pesinat;
    }

    
    @Column(name="borcluAd", length=45)
    public String getBorcluAd() {
        return this.borcluAd;
    }
    
    public void setBorcluAd(String borcluAd) {
        this.borcluAd = borcluAd;
    }

    
    @Column(name="borcluTelefon", length=45)
    public String getBorcluTelefon() {
        return this.borcluTelefon;
    }
    
    public void setBorcluTelefon(String borcluTelefon) {
        this.borcluTelefon = borcluTelefon;
    }

    
    @Column(name="kefilAd", length=45)
    public String getKefilAd() {
        return this.kefilAd;
    }
    
    public void setKefilAd(String kefilAd) {
        this.kefilAd = kefilAd;
    }

    
    @Column(name="sozlesmeNot", length=45)
    public String getSozlesmeNot() {
        return this.sozlesmeNot;
    }
    
    public void setSozlesmeNot(String sozlesmeNot) {
        this.sozlesmeNot = sozlesmeNot;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sozlesmeVadeTarih", length=10)
    public Date getSozlesmeVadeTarih() {
        return this.sozlesmeVadeTarih;
    }
    
    public void setSozlesmeVadeTarih(Date sozlesmeVadeTarih) {
        this.sozlesmeVadeTarih = sozlesmeVadeTarih;
    }




}


